# Generated by Django 4.1.2 on 2022-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-create_date",),
            },
        ),
    ]
